### ISSUE TITLE
Дизайн окружения

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/PANDA-KILLER#13]
Нарисовать локацию -- кофейная плантация на диком западе.
1. Песочный ландшафт, за основу взять песочные тайлы 8bit-panda
2. Кофейные кусты. Можно отойти от реализма ради красивой картинки
3. Произвольные деревянные строения (tilemap)
4. Произвольные "земляные" платформы
6. Предложить основной цвет для фона
7. Декорации -- растения, другие детали
8. Придумать висячие платформы, по типу тех что на картинке
![cave](https://github.com/user-attachments/assets/e308a6a3-6c14-43fa-bc43-bf7124d19802)

При необходимости можете добавлять цвета в палитру

**Comment by VIPigeon** [comment]
Важная правка по поводу строений: их внешний вид должен быть "изнутри". У нас есть "осязаемые" стены на первом плане и неосязаемые на фоне
![image](https://github.com/user-attachments/assets/cff3ea3d-4a9c-4dff-bd1a-4605459da537)

В нашей стилистике хороших примеров не нашел

**Comment by kawaii-Code** [comment]
Как в террарии короче 🌲
