### ISSUE TITLE
Правки по игроку

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/PANDA-KILLER#16]
1. Отделить линии удара от игрока и сделать их дальше, как удар в Hollow Knight (следуйте [референсу удара](https://youtube.com/clip/UgkxcShLbArwwIJhFLVuEsfZ0AChtiRagX7E?si=uqG1Cg5Cm0A44umP))
2. Добавить удар в воздухе вниз ([по референсу из Hollow Knight](https://youtube.com/clip/UgkxuW_3yBjkC1_FBgG0LGXpjOD6dyi51sve?si=GFBNZ4fTv7PkdGtk))
3. Добавить прыжок от стены (и след к нему) ([референс](https://youtu.be/zDevkNHqWKU?si=PcRNU5SVJt8jwkm6))
4. В анимации прыжка и удара в прыжке **не надо** поднимать игрока вверх относительно центра. (Сейчас это так). См. коммент Вани под issue

**Comment by kawaii-Code** [comment]
От меня: спрайта прыжка поднимают спрайт игрока выше, так не должно быть. Двигается он программно, а в спрайте должен оставаться на одинаковой высоте. Посмотрите в этой гифке как я бьюсь головой об зеленую штуку, игрок прямо сильно внутрь залетает:

![video5](https://github.com/user-attachments/assets/22e4ea1e-4cd1-4e25-b081-2f241a78055e)
