### ISSUE TITLE
Внедрение анимаций игрока

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/PANDA-KILLER#19]
1. Правильно зациклить анимацию скольжения по стене
2. Последний кадр удара должен быть дольше чем остальные
3. След от прыжка сделать отдельно от игрока
4. Проигрывать анимацию атаки до конца
5. Пофиксить проджект-тайл атаки игрока

**Comment by kawaii-Code** [comment]
1 2 4 5 есть. Остался гроб 💀

**Comment by kawaii-Code** [comment]
Нужно подумать над эффектом сползание по стене и над атакой, но это уже в будущем
