### ISSUE TITLE
Привязать камеру к игроку

### ISSUE THREAD

**Issue by VIPigeon** [VIPigeon/PANDA-KILLER#6]
Нужно, чтобы при прыжках камера **не** дергалась вверх-вниз.

Как вариант, окно камеры можно сделать таким. Возможно, у тебя есть другое решение этой проблемы
![window](https://github.com/user-attachments/assets/d169d0cb-4a58-4a94-84fe-c3f8a149347e)

**Comment by kawaii-Code** [comment]
Изи. Камеру как в нормальных платформерах я так и не запилил 😎
